[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["cd services/api && npm install"]

[phases.build]
cmds = [
  "cd services/api",
  "npm run build"
]

[start]
cmd = "cd services/api && node dist/main.js"
