[phases.setup]
nixPkgs = ["openssl", "ca-certificates"]

[phases.install]
cmds = [
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build --workspace=api-deploy"
]

[phases.prisma]
cmds = [
  "npx prisma generate --schema=api-deploy/prisma/schema.prisma"
]

[phases.start]
cmds = [
  "node api-deploy/dist/main.js"
]

[start]
cmd = "node api-deploy/dist/main.js"