[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install --prefix api-deploy"]

[phases.build]
cmds = ["npx --prefix api-deploy prisma generate", "npm run build --prefix api-deploy"]

[start]
cmd = "cd api-deploy && node dist/main.js"
