export const AUTH_COPY = {
  login: {
    title: 'Connexion',
    subtitle: 'Accède à SKY PLAY avec ton compte.',
    emailLabel: 'Email',
    passwordLabel: 'Mot de passe',
    submit: 'Se connecter',
    submitLoading: 'Connexion…',
    noAccount: 'Pas de compte ?',
    createAccount: 'Créer un compte',
    socialTitle: 'Social login (préparé)',
    googleSoon: 'Google (bientôt)',
    discordSoon: 'Discord (bientôt)',
  },
  signup: {
    title: 'Créer un compte',
    subtitle: 'Rejoins les challenges et gagne des rewards.',
    emailLabel: 'Email',
    usernameLabel: 'Username',
    passwordLabel: 'Mot de passe',
    submit: 'Créer mon compte',
    submitLoading: 'Création…',
    haveAccount: 'Déjà un compte ?',
    login: 'Se connecter',
    confirmTitle: 'Confirmer ton email',
    confirmSubtitle: "Entre le code reçu par email pour activer ton compte.",
    confirmCta: 'Confirmer mon compte',
    resend: 'Renvoyer le code',
    codeResent: 'Code renvoyé. Vérifie tes emails.',
    confirmed: 'Compte confirmé. Tu peux te connecter.',
  },
} as const;
